// ============================================================================
// constraints.js  -  shared geometry pinned to constraints.md v1.0
// ============================================================================
// Every implementation in this directory imports from here. Version mismatch
// with constraints.md aborts the harness before any path runs (see harness.js).
// Do not edit this file without bumping SPEC_VERSION and the constraints.md
// header together. Keep them pinned.
// ============================================================================

"use strict";

const SPEC_VERSION = "1.0";

// ---- 1. Dimensions ---------------------------------------------------------
// Order matters: dim index is array position.
const DIMS = Object.freeze([
  Object.freeze({ name: "credit",     values: Object.freeze(["prime", "near-prime", "sub-prime"]) }),
  Object.freeze({ name: "product",    values: Object.freeze(["mortgage", "personal", "auto", "business-line"]) }),
  Object.freeze({ name: "applicant",  values: Object.freeze(["individual", "joint", "business", "trust"]) }),
  Object.freeze({ name: "residency",  values: Object.freeze(["domestic", "foreign", "diplomatic"]) }),
  Object.freeze({ name: "income",     values: Object.freeze(["under50", "50to100", "100to250", "over250"]) }),
  Object.freeze({ name: "employment", values: Object.freeze(["employed", "self-employed", "retired", "student", "unemployed"]) })
]);

const STATE_SPACE_SIZE = DIMS.reduce((n, d) => n * d.values.length, 1); // 2880

// ---- 2. Output defaults ----------------------------------------------------
const DEFAULTS = Object.freeze({
  sdf: -1,
  reg: "VALID",
  deny: "",
  rt: "UNCLASSIFIED",
  rth: 0,
  doc: "BASIC"
});

// ---- 3. Constraints (11 total, ordered) ------------------------------------
// Declaration order matches constraints.md section 3.
// The resolution procedure (section 4) applies rules in order and lets later
// rules override earlier ones on shared output keys.
const CONSTRAINTS = Object.freeze([
  // Credit-tier defaults (1-key specificity)
  Object.freeze({ when: Object.freeze({ credit: "prime" }),
                  then: Object.freeze({ rt: "A-PREFERRED", rth: 160, doc: "BASIC" }) }),
  Object.freeze({ when: Object.freeze({ credit: "near-prime" }),
                  then: Object.freeze({ rt: "B-STANDARD",  rth: 130, doc: "ENHANCED" }) }),
  Object.freeze({ when: Object.freeze({ credit: "sub-prime" }),
                  then: Object.freeze({ rt: "C-ELEVATED",  rth:  95, doc: "ENHANCED" }) }),

  // Residency uplifts (1-key specificity)
  Object.freeze({ when: Object.freeze({ residency: "foreign" }),
                  then: Object.freeze({ doc: "ENHANCED" }) }),
  Object.freeze({ when: Object.freeze({ residency: "diplomatic" }),
                  then: Object.freeze({ doc: "MAXIMUM" }) }),

  // Denials (2- and 3-key specificity)
  Object.freeze({ when: Object.freeze({ credit: "sub-prime", product: "business-line" }),
                  then: Object.freeze({ sdf: 1, deny: "SubPrime cannot hold BusinessLine" }) }),
  Object.freeze({ when: Object.freeze({ residency: "foreign", product: "mortgage", credit: "sub-prime" }),
                  then: Object.freeze({ sdf: 1, deny: "Foreign SubPrime Mortgage not underwriteable" }) }),
  Object.freeze({ when: Object.freeze({ employment: "unemployed", product: "mortgage" }),
                  then: Object.freeze({ sdf: 1, deny: "Mortgage requires income source" }) }),
  Object.freeze({ when: Object.freeze({ employment: "student", product: "business-line" }),
                  then: Object.freeze({ sdf: 1, deny: "Student cannot hold BusinessLine" }) }),
  Object.freeze({ when: Object.freeze({ applicant: "trust", product: "personal" }),
                  then: Object.freeze({ sdf: 1, deny: "Trust cannot hold Personal" }) }),
  Object.freeze({ when: Object.freeze({ income: "under50", product: "mortgage" }),
                  then: Object.freeze({ sdf: 1, deny: "Mortgage requires minimum qualifying income" }) })
]);

// ---- 5. Canonical string tables --------------------------------------------
// Index 0 is always the default / empty value for its column.
const RT_TABLE = Object.freeze([
  "UNCLASSIFIED", "A-PREFERRED", "B-STANDARD", "C-ELEVATED"
]);
const DOC_TABLE = Object.freeze([
  "BASIC", "ENHANCED", "MAXIMUM"
]);
const REG_TABLE = Object.freeze([
  "VALID", "DENIED"
]);
const DENY_TABLE = Object.freeze([
  "",                                                 // 0
  "SubPrime cannot hold BusinessLine",                // 1
  "Foreign SubPrime Mortgage not underwriteable",     // 2
  "Mortgage requires income source",                  // 3
  "Student cannot hold BusinessLine",                 // 4
  "Trust cannot hold Personal",                       // 5
  "Mortgage requires minimum qualifying income"       // 6
]);

// ---- Helpers ---------------------------------------------------------------

// Given a dim name, return its index (0..5) or throw.
function dimIndex(name) {
  for (let i = 0; i < DIMS.length; i++) {
    if (DIMS[i].name === name) return i;
  }
  throw new Error("unknown dim: " + name);
}

// Given a dim index and a value string, return its value index or throw.
function valueIndex(dimIdx, value) {
  const vs = DIMS[dimIdx].values;
  for (let i = 0; i < vs.length; i++) {
    if (vs[i] === value) return i;
  }
  throw new Error("unknown value '" + value + "' in dim " + DIMS[dimIdx].name);
}

// Given a string and a table, return its index or -1 if absent.
function lookupIndex(table, s) {
  for (let i = 0; i < table.length; i++) {
    if (table[i] === s) return i;
  }
  return -1;
}

// Canonical enumeration: last dim varies fastest.
// For coord index i, returns [c0, c1, ..., c5].
function unpackCoord(i) {
  const out = new Array(DIMS.length);
  let remainder = i;
  for (let d = DIMS.length - 1; d >= 0; d--) {
    const card = DIMS[d].values.length;
    out[d] = remainder % card;
    remainder = Math.floor(remainder / card);
  }
  return out;
}

// Reverse: a coord array -> a single index.
function packCoord(coord) {
  let idx = 0;
  for (let d = 0; d < DIMS.length; d++) {
    idx = idx * DIMS[d].values.length + coord[d];
  }
  return idx;
}

// Bit-packed u32 form (specified in constraints.md section 1).
// d0 | (d1<<3) | (d2<<6) | (d3<<9) | (d4<<12) | (d5<<15)
// This is the GPU-side wire format, separate from the linear coord_index above.
function packCoordU32(coord) {
  return (
    (coord[0] & 0x7) |
    ((coord[1] & 0x7) <<  3) |
    ((coord[2] & 0x7) <<  6) |
    ((coord[3] & 0x7) <<  9) |
    ((coord[4] & 0x7) << 12) |
    ((coord[5] & 0x7) << 15)
  ) >>> 0;
}

function unpackCoordU32(packed) {
  return [
    (packed >>>  0) & 0x7,
    (packed >>>  3) & 0x7,
    (packed >>>  6) & 0x7,
    (packed >>>  9) & 0x7,
    (packed >>> 12) & 0x7,
    (packed >>> 15) & 0x7
  ];
}

// ---- Exports ---------------------------------------------------------------

module.exports = {
  SPEC_VERSION,
  DIMS,
  STATE_SPACE_SIZE,
  DEFAULTS,
  CONSTRAINTS,
  RT_TABLE,
  DOC_TABLE,
  REG_TABLE,
  DENY_TABLE,
  dimIndex,
  valueIndex,
  lookupIndex,
  unpackCoord,
  packCoord,
  packCoordU32,
  unpackCoordU32
};
