// ============================================================================
// constraints.mjs  -  ES module re-export of constraints.js
// ============================================================================
// Browser environment imports from here. Node environment (tests) uses
// constraints.js directly. Both files MUST stay synchronized. This file is
// generated by running `node build-mjs.js`.
//
// If you edit constraints.js, regenerate this file. The harness checks
// SPEC_VERSION in both and aborts on mismatch.
// ============================================================================

const SPEC_VERSION = "1.0";

const DIMS = Object.freeze([
  Object.freeze({ name: "credit",     values: Object.freeze(["prime", "near-prime", "sub-prime"]) }),
  Object.freeze({ name: "product",    values: Object.freeze(["mortgage", "personal", "auto", "business-line"]) }),
  Object.freeze({ name: "applicant",  values: Object.freeze(["individual", "joint", "business", "trust"]) }),
  Object.freeze({ name: "residency",  values: Object.freeze(["domestic", "foreign", "diplomatic"]) }),
  Object.freeze({ name: "income",     values: Object.freeze(["under50", "50to100", "100to250", "over250"]) }),
  Object.freeze({ name: "employment", values: Object.freeze(["employed", "self-employed", "retired", "student", "unemployed"]) })
]);

const STATE_SPACE_SIZE = DIMS.reduce((n, d) => n * d.values.length, 1);

const DEFAULTS = Object.freeze({
  sdf: -1, reg: "VALID", deny: "", rt: "UNCLASSIFIED", rth: 0, doc: "BASIC"
});

const CONSTRAINTS = Object.freeze([
  Object.freeze({ when: Object.freeze({ credit: "prime" }),
                  then: Object.freeze({ rt: "A-PREFERRED", rth: 160, doc: "BASIC" }) }),
  Object.freeze({ when: Object.freeze({ credit: "near-prime" }),
                  then: Object.freeze({ rt: "B-STANDARD",  rth: 130, doc: "ENHANCED" }) }),
  Object.freeze({ when: Object.freeze({ credit: "sub-prime" }),
                  then: Object.freeze({ rt: "C-ELEVATED",  rth:  95, doc: "ENHANCED" }) }),
  Object.freeze({ when: Object.freeze({ residency: "foreign" }),
                  then: Object.freeze({ doc: "ENHANCED" }) }),
  Object.freeze({ when: Object.freeze({ residency: "diplomatic" }),
                  then: Object.freeze({ doc: "MAXIMUM" }) }),
  Object.freeze({ when: Object.freeze({ credit: "sub-prime", product: "business-line" }),
                  then: Object.freeze({ sdf: 1, deny: "SubPrime cannot hold BusinessLine" }) }),
  Object.freeze({ when: Object.freeze({ residency: "foreign", product: "mortgage", credit: "sub-prime" }),
                  then: Object.freeze({ sdf: 1, deny: "Foreign SubPrime Mortgage not underwriteable" }) }),
  Object.freeze({ when: Object.freeze({ employment: "unemployed", product: "mortgage" }),
                  then: Object.freeze({ sdf: 1, deny: "Mortgage requires income source" }) }),
  Object.freeze({ when: Object.freeze({ employment: "student", product: "business-line" }),
                  then: Object.freeze({ sdf: 1, deny: "Student cannot hold BusinessLine" }) }),
  Object.freeze({ when: Object.freeze({ applicant: "trust", product: "personal" }),
                  then: Object.freeze({ sdf: 1, deny: "Trust cannot hold Personal" }) }),
  Object.freeze({ when: Object.freeze({ income: "under50", product: "mortgage" }),
                  then: Object.freeze({ sdf: 1, deny: "Mortgage requires minimum qualifying income" }) })
]);

const RT_TABLE   = Object.freeze(["UNCLASSIFIED", "A-PREFERRED", "B-STANDARD", "C-ELEVATED"]);
const DOC_TABLE  = Object.freeze(["BASIC", "ENHANCED", "MAXIMUM"]);
const REG_TABLE  = Object.freeze(["VALID", "DENIED"]);
const DENY_TABLE = Object.freeze([
  "",
  "SubPrime cannot hold BusinessLine",
  "Foreign SubPrime Mortgage not underwriteable",
  "Mortgage requires income source",
  "Student cannot hold BusinessLine",
  "Trust cannot hold Personal",
  "Mortgage requires minimum qualifying income"
]);

function dimIndex(name) {
  for (let i = 0; i < DIMS.length; i++) if (DIMS[i].name === name) return i;
  throw new Error("unknown dim: " + name);
}

function valueIndex(dimIdx, value) {
  const vs = DIMS[dimIdx].values;
  for (let i = 0; i < vs.length; i++) if (vs[i] === value) return i;
  throw new Error("unknown value '" + value + "' in dim " + DIMS[dimIdx].name);
}

function lookupIndex(table, s) {
  for (let i = 0; i < table.length; i++) if (table[i] === s) return i;
  return -1;
}

function unpackCoord(i) {
  const out = new Array(DIMS.length);
  let remainder = i;
  for (let d = DIMS.length - 1; d >= 0; d--) {
    const card = DIMS[d].values.length;
    out[d] = remainder % card;
    remainder = Math.floor(remainder / card);
  }
  return out;
}

function packCoord(coord) {
  let idx = 0;
  for (let d = 0; d < DIMS.length; d++) {
    idx = idx * DIMS[d].values.length + coord[d];
  }
  return idx;
}

function packCoordU32(coord) {
  return (
    (coord[0] & 0x7) |
    ((coord[1] & 0x7) <<  3) |
    ((coord[2] & 0x7) <<  6) |
    ((coord[3] & 0x7) <<  9) |
    ((coord[4] & 0x7) << 12) |
    ((coord[5] & 0x7) << 15)
  ) >>> 0;
}

function unpackCoordU32(packed) {
  return [
    (packed >>>  0) & 0x7,
    (packed >>>  3) & 0x7,
    (packed >>>  6) & 0x7,
    (packed >>>  9) & 0x7,
    (packed >>> 12) & 0x7,
    (packed >>> 15) & 0x7
  ];
}

export {
  SPEC_VERSION, DIMS, STATE_SPACE_SIZE, DEFAULTS, CONSTRAINTS,
  RT_TABLE, DOC_TABLE, REG_TABLE, DENY_TABLE,
  dimIndex, valueIndex, lookupIndex,
  unpackCoord, packCoord, packCoordU32, unpackCoordU32
};
